name: Compile AzureDynDNS

on:
  pull_request:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      publish-artifacts:
        description: Publish runtime artifacts
        required: false
        type: boolean
        default: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity minimal

  publish:
    if: ${{ inputs.publish-artifacts && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'workflow_call') }}
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-runtime: ['linux-arm', 'linux-x64']
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x

      - name: Publish single executable file for ${{ matrix.target-runtime }}
        run: dotnet publish src/AzureDynDns/AzureDynDns.csproj -c Release -r ${{ matrix.target-runtime }} /p:PublishSingleFile=true -o publish

      - name: Upload artifact for ${{ matrix.target-runtime }}
        uses: actions/upload-artifact@v4
        with:
          name: AzureDynDNS-${{ matrix.target-runtime }}
          path: publish