name: Compile AzureDynDNS

on: [push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run tests
      run: dotnet test
  
  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Available .NET Core Runtime IDentifiers (RID)
        # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
        target-runtime: ['linux-arm', 'linux-x64']
    steps:
    - uses: actions/checkout@v2
    - name: Publish single executable file for  ${{ matrix.target-runtime }}
      run:  dotnet publish src/AzureDynDns/AzureDynDns.csproj -c Release -r ${{ matrix.target-runtime }} /p:PublishSingleFile=true -o publish
    - name: Upload artifact for  ${{ matrix.target-runtime }}
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name, without .zip extension
        name: AzureDynDNS-${{ matrix.target-runtime }}
        # Directory containing files to upload
        path: publish