name: Compile AzureDynDNS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish single exe file
      run:  dotnet publish -c Release -r linux-arm /p:PublishSingleFile=true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name, without .zip extension
        name: AzureDynDNS
        # Directory containing files to upload
        path: src/AzureDynDns/bin/Release/netcoreapp3.1/linux-arm/publish